import './globals.css'
import { Roboto } from 'next/font/google'
import Navbar from '@/components/Navbar'

const roboto = Roboto({
  weight: ['100', '300', '400'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Online Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
