import './globals.css'
import { Open_Sans } from 'next/font/google'
import Navbar from '@/components/Navbar'

const opensans = Open_Sans({
  weight: ['300', '400', '500', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Online Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={opensans.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
